### ISSUE TITLE
Rich Media Support

### ISSUE THREAD

**Issue by brysonreece** [highsidelabs/walmart-api-php#1]
Hey there, great package you've put together! I was wondering if there were any plans to integrate Walmart's Rich Media functionality using the Content Provider API? I've poked around the source but haven't found any reference to it.

https://developer.walmart.com/doc/us/us-cp/us-cp-feeds/#3410

If it's a matter of workload, I'd be happy to take a look at submitting a PR if you're open to contributions!

**Comment by jlevers** [comment]
Whoops, I had the generator set up to ignore endpoints that didn't have `/v3/` in them, thinking that that would include all up-to-date ones, but missed the Rich Media functionality. All those endpoints should be available in the latest version, `v0.3.0`. Give it a shot and let me know if you encounter any problems – I know there are some issues with return types scattered around the package.

Out of curiosity, how'd you find this package? You seem to have stumbled across it almost immediately after I released it!

**Comment by brysonreece** [comment]
Sounds good, I'll give it a go!

As for how I came across this package, it was one of the first results when searching for "walmart php" on GitHub and sorting by "most recently updated"
