### ISSUE TITLE
Method prices does not exist

### ISSUE THREAD

**Issue by nidhi-simzia** [highsidelabs/walmart-api-php#11]
$this->config = new Configuration([
                'clientId' => $account->client_id,
                'clientSecret' => $account->client_secret,
                'country' => Country::US,
            ]);

            $this->WMPObjects = Walmart::marketplace($this->config);
            $itemsApi = $this->WMPObjects->prices();
            
Got error Method prices does not exist. 
Using "highsidelabs/walmart-api": "v0.6.1",

**Comment by nidhi-simzia** [comment]
I have made changes in Vendor file, MarketplaceApi.php Only for US for now,

'prices' => [
            Country::CA => CA\PriceApi::class,
            Country::MX => MX\PriceApi::class,
            Country::US => US\PricesApi::class,
        ],
        
        Now working but I guess It should be changed in Repo too.

**Comment by jlevers** [comment]
This should be fixed in `v0.6.3`.
