### ISSUE TITLE
ClientID and ClientSecret

### ISSUE THREAD

**Issue by loveisbluenova** [highsidelabs/walmart-api-php#3]
ClientID and ClientSecret are not exist in Walmart CA.
I can get only consumerID and privateKey.
How can use this package without ClientID and ClientSecret?

**Comment by jlevers** [comment]
Thanks for surfacing this issue. I don't have credentials outside the US, so I didn't realize that other marketplaces don't use the client ID or client secret at all. I've fixed this issue in `v0.4.0` by moving those values from required `Configuration` constructor parameters to optional keys to the `$options` array passed to the constructor. Note that the `$options` array is now the _only_ parameter to the `Configuration` constructor.
